### ISSUE TITLE
APPLICATION ERROR #2502

### ISSUE THREAD

**Issue by King-GO** [Imatic-IT/imatic-mantis-autocomplete#2]
Page "config" does not exist in Plugin "ImaticAutocomplete".

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

**Comment by matejbrodziansky** [comment]
Fixed https://github.com/Imatic-IT/imatic-mantis-autocomplete/commit/e11d255056ee3c47c40b9f436520851e7f139fec
